project:
  type: website
  
execute:
  freeze: auto  # re-render only when source changes

website:
  title: "Jordan Hutchings"
  favicon: "img/favicon2.png"
  google-analytics: 
    cookie-consent: true
    tracking-id: "G-QH21BBYP6K"
    anonymize-ip: true
  navbar:
    title: Jordan Hutchings
    left:
      - href: blog.qmd
        text: Blog
      - href: research.qmd
        text: Research
      - href: pdf/cv.pdf
        text: CV
      - href: misc.qmd
        text: Misc
    right:
      - icon: github
        href: https://github.com/jjhutchi
  page-footer:
    left: "Â© Copyright 2023 Jordan Hutchings."
format:
  html:
    theme: 
      light: [sandstone, _light.scss]
      dark: [sandstone, _dark.scss]
    css: styles.css
    editor: source